---
title: "Garrett_Paper"
output:
  pdf_document: default
  html_document: default
date: "2024-11-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

  The third model that we decided to use for this project was an ARIMA model, which is a model that we have not discussed in class but that we thought would provide a promising opportunity to work with the time series data. ARIMA stands for Autoregressive Integrated Moving Average and it's main goal is to "use time series data to either better understand the data set or predict future trends" (Hayes). For us, this meant that an ARIMA model would hopefully be able to better handle the time series data that we were using and could then use its understanding of the data to make predictions if we set the parameters of the model to the correct values. It also meant that, since we had a consistent stream of sales data over multiple years for Corporación Favorita and could see trends, future sales would most likely be more correlated to past sales which is exactly what ARIMA models are used for. ARIMA models are also extremely valuable when it comes to autocorrelation, which is "the degree of correlation of the same variables between two successive time intervals" (Taylor). Essentially, this means that ARIMA models can use a lagged value of a variable and compare it to the original value to optimally find patterns in the data that are related to specific time periods. This was especially valuable when it came to this data set because we needed to identify whether weekly or yearly trends (or both) impacted the overall sales data. The structure of an ARIMA model comes down to the actual code itself and the different parameters that we included within the model to attempt to better capture the relationships in the data. In our model specifically, it can be seen that there are 3 integers next to the ARIMA residual plots in the form [5,1,1]. In this case the "ARIMA" function was taken from the "forecast" package, and 5, 1, and 1 are the main parameters of the model. The 5 specifies the the number of past observations that are used to predict the current value it is tracking and is called the autoregressive term. The first 1 is used to make sure the time series is "differenced" (previous value subtracted from current value) once so that the data then becomes stationary. It is extremely important for time series data to be stationary because this ensures that "mean, variance, and autocorrelation — remain unwavering over time. . . [ARIMA] models rely on the constancy of statistical properties like mean and variance over time. Non-stationary data can lead to unreliable model outputs and inaccurate predictions, just because the models aren’t expecting it" (Tate). For this specific model, we found that just one differencing of the data was enough to create a solid stationary base for the model to predict on. The second 1 in the model is the number of lagged forecast errors that are used to predict. With a value of one, this means that the model uses the most recent error to adjust its prediction, and a value of one also makes sure that overfitting is avoided. With this lagged forecast error set to 1 the model can better understand patterns outside of the scope of the first two parameters and can better predict values that are not accounted for by differencing or the autoregressive term. These components are the base of the ARIMA model in general, but for our specific project we also used a more advanced version of the model which implements seasonal parameters to further increase prediction accuracy and data understanding. The seasonal parameters follow the same patterns as the original model, with the the second set of parameters (2,1,2) being the seasonal terms and the [7] being the frequency term. The 7 is the driving factor for how the seasonal terms are used within the model, meaning the first 2 represents 2 lagged terms for 7 and 14 days respectively, the 1 once again represents a single difference for the current term minus the term from 7 days prior, and the second 2 represents two lagged forecast errors from 7 and 14 days prior. Using both the base ARIMA parameters as well as the seasonal capability of the ARIMA model within the forecast package allowed us to tweak the model in many different ways to help with our final predictions. This also allowed us to better capture autocorrelation and seasonal properties within the time series data and optimized our analysis process to better forecast these predictions and understand the nuances of the data.
=======
  The third model that we decided to use for this project was an ARIMA model, which is a model that we have not discussed in class but that we thought would provide a promising opportunity to work with the time series data. ARIMA stands for Autoregressive Integrated Moving Average and it's main goal is to "use time series data to either better understand the data set or predict future trends" (Hayes). For us, this meant that an ARIMA model would hopefully be able to better handle the time series data that we were using and could then use its understanding of the data to make predictions if we set the parameters of the model to the correct values. It also meant that, since we had a consistent stream of sales data over multiple years for Corporación Favorita and could see trends, future sales would most likely be more correlated to past sales which is exactly what ARIMA models are used for. ARIMA models are also extremely valuable when it comes to autocorrelation, which is "the degree of correlation of the same variables between two successive time intervals" (Taylor). Essentially, this means that ARIMA models can use a lagged value of a variable and compare it to the original value to optimally find patterns in the data that are related to specific time periods. This was especially valuable when it came to this data set because we needed to identify whether weekly or yearly trends (or both) impacted the overall sales data. The structure of an ARIMA model comes down to the actual code itself and the different parameters that we included within the model to attempt to better capture the relationships in the data. In our model specifically, it can be seen that there are 3 integers next to the ARIMA residual plots in the form [5,1,1]. In this case the "ARIMA" function was taken from the "forecast" package, and 5, 1, and 1 are the main parameters of the model. The 5 specifies the the number of past observations that are used to predict the current value it is tracking and is called the autoregressive term. The first 1 is used to make sure the time series is "differenced" (previous value subtracted from current value.) once so that the data then becomes stationary. It is extremely important for time series data to be stationary because this ensures that "mean, variance, and autocorrelation — remain unwavering over time. . . [ARIMA] models rely on the constancy of statistical properties like mean and variance over time. Non-stationary data can lead to unreliable model outputs and inaccurate predictions, just because the models aren’t expecting it" (Tate). For this specific model, we found that just one differencing of the data was enough to create a solid stationsary base for the model to predict on. The second 1 in the model is the number of lagged forecast errors that are used to predict. With a value of one, this means that the model uses the most recent error to adjust its prediction, and a value of one also makes sure that overfitting is avoided. With this lagged forecast error set to 1 the model can better understand patterns outside of the scope of the first two parameters and can better predict values that are not accounted for by differencing or the autoregressive term. These components are the base of the ARIMA model in general, but for our specific project we also used a more advanced version of the model which implements seasonal parameters to further increase prediction accuracy and data understanding. The seasonal parameters follow the same patterns as the original model, with the the second set of parameters (2,1,2) being the seasonal terms and the [7] being the frequency term. The 7 is the driving factor for how the seasonal terms are used within the model, meaning the first 2 represents 2 lagged terms for 7 and 14 days respectively, the 1 once again represents a single difference for the current term minus the term from 7 days prior, and the second 2 represents two lagged forecast errors from 7 and 14 days prior. Using both the base ARIMA parameters as well as the seasonal capability of the ARIMA model within the forecast package allowed us to tweak the model in many different ways to help with our final predictions. This also allowed us to better capture autocorrelation and seasonal properties within the time series data and optimized our analysis process to better forecast these predictions and understand the nuances of the data.

  Throughout the trial and error process of this model the most common issue that was difficult to overcome was the actual tweaking of the ARIMA parameters to reduce autocorrelation in residuals. Even with the seasonal parameters allowing us to better capture the time series trends within the data, specific lags throughout each iteration of the model were experiencing significant residual autocorrelation that drastically fell beyond the bounds of the 95% confidence interval that was being used. This was an indication to us that the models that we were testing weren't actually capturing the entirety of the time dependent patters that were present in the data, and because of this our submissions to the competition were garnering an extremely high RMLSE. The first submission received a score of 10.27155, further confirming our need for the model to better understand the structure of the seasonal patterns through some other means of analysis. Our solution to this problem actually came from the prerequisite course that Kaggle recommends to users when engaging in this competition, the "Time Series" course. In that course the use of Fourier features is explained as "pairs of sine and cosine curves, one pair for each potential frequency in the season starting with the longest" (Holbrook). Essentially, for each Fourier feature in our model (K = 3), there is a sine and cosine pairing that then attempts to capture increasingly granular time series patterns within the specified frequency. In this case, with the frequency being 7 (days), the first pair of sine and cosine 
curves attempts to capture the most basic cyclic pattern within the 7 day cycle. The second feature then looks for the next pattern within a more constrained period such as a mid week pattern. Finally, the third feature goes even deeper into the data and looks for even finer patterns that could contribute to the overall model's understanding of the data. While Fourier features are more commonly used for annual time series patterns, in our case, our base ARIMA model wasn't able to capture all of the weekly patterns that were occurring throughout this period. After we added the K=3 Fourier features to the model, our overall RMLSE went down significantly to a value of 3.93254. This decrease in the error term of the model was almost entirely caused by the introduction of the Fourier terms, and proved that these features coupled with our base seasonal ARIMA model provided a strong understanding of the time series patterns within the data set. The other main issue that we encountered while trying to improve the model was the fact that we needed to train the model on the entirety of the sales data which spans two variables. The first being the store_nbr variable which was the sales for individual stores, and the second being the family variable which was the sales for different product categories. In order for us to simplify the the analysis and training of the model, we aggregrated these two variables to create a total sales metric that was the sum of the two variables by day. This allowed for the ARIMA model to fully capture the entirety of sales on each given day and then predict on that data. This greatly increased the simplicity of the model process, because we didn't have to train multiple models on the different variables, but it also created an issue when trying to output the predicted values for submission. Since this sales data was now aggregated, we couldn't just put these values back into our output to then turn in to the competition. Instead, we had to deaggregate the data back into its original form so that there were individual predictions for each ID. Unfortunately, in order to do this, we had to then find a solution as to how we would represent the sales data for both the variables in the final submission. A more advanced solution could have been a Bayesian data structure that could have shared information about the entirety of the data set across two separate models, which would have then not required the aggregation of the data in the first place. However, this was not something that we had the knowledge to do, and would have been outside the scope of this class. Instead, we found that finding a general proportion of total sales for both the store_nbr and family variables and then using that proportion to estimate the percentage of daily total sales in our final submission would be the simplest option. By doing this, we could then have a standard factor of sales between the two variables which would reduce the skewing of total sales data by either one of the variables. This method is definitely not the most precise or efficient use of the ARIMA model, but it did allow us to try to reduce the overall bias that we had created by aggregating the data in the first place. Overall, these were our two main issues that came up throughout or analysis and model creation, and they were difficult issues to tackle as we had to find new solutions to a model that we had not worked with before. However, our understanding of the model itself and as well as our research on different solutions such as Fourier features allowed us to create a simple ARIMA model that predicted quite well given our limited knowledge of the subject.

Hayes, Adam. “Autoregressive Integrated Moving Average (ARIMA) Prediction Model.” Investopedia, Investopedia, www.investopedia.com/terms/a/autoregressive-integrated-moving-average-arima.asp. Accessed 20 Nov. 2024.

Taylor, Sebastian. “Autocorrelation.” Corporate Finance Institute, 21 Nov. 2023, corporatefinanceinstitute.com/resources/data-science/autocorrelation/. 

Tate, Andrew. “Understanding the Importance of Stationarity in Time Series.” Hex, 1 Dec. 2023, hex.tech/blog/stationarity-in-time-series/. 

Holbrook, Ryan. “Store Sales - Time Series Forecasting.” Kaggle, Kaggle, www.kaggle.com/competitions/store-sales-time-series-forecasting/overview. Accessed 25 Nov. 2024. 