---
title: "Lauren and Jillian EDA"
output: html_document
date: "2024-11-14"
---

```{r setup, include=FALSE}
rm(list = ls())
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# install packages and load libraries
#install.packages("ranger")
#install.packages("ModelMetrics")
library(ModelMetrics)
library(parallel)
library(readr)
library(dplyr)
library(leaps)
library(ggplot2)
library(glmnet)
library(ISLR)
library(dials)
library(tidymodels)
library(randomForest)
library(ranger)
library(vip)
library(parsnip)
library(lubridate)
library(rsample)
```

```{r}
# load data
final_train_lags <- read_csv("/data/accounts/fa24/garretthayden/DSCI445/FinalProject2/Data//final_train_lags.csv")

final_test_lags <- read_csv("/data/accounts/fa24/garretthayden/DSCI445/FinalProject2/Data/final_test_lags.csv")
```


```{r}
# Prepare data to be processed in a random forest
str(final_train_lags)

# Replace NA values in holiday binary predictors with 0
final_train_lags <- final_train_lags %>%
  mutate(national_holiday = ifelse(is.na(national_holiday), 0, national_holiday),
         state_holiday = ifelse(is.na(state_holiday), 0, state_holiday),
         city_holiday = ifelse(is.na(city_holiday), 0, city_holiday))

# Factorize text predictors
final_train_lags <- final_train_lags %>%
  mutate(store_nbr = factor(store_nbr), family = factor(family), city = factor(city), state = factor(state), type = factor(type)) %>%
        dplyr::mutate(across(where(is.factor), as.integer))

# Use forward and backward fill to replace NA values in daily oil price
final_train_lags <- final_train_lags %>%
  arrange(date) %>%
  fill(dcoilwtico, .direction = "down")%>%
  fill(dcoilwtico, .direction = "up")

# Use forward and backward fill to replace NA transaction values 
final_train_lags <- final_train_lags %>%
  arrange(date) %>%
  fill(transactions, .direction = "down")%>%
  fill(transactions, .direction = "up")

# Drop the observations with NA values for sales lags (primarily from beginning of dataset)
final_train_lags <- final_train_lags %>%
  drop_na(sales_lag_1, sales_lag_7,sales_lag_30,sales_lag_60,sales_lag_90,sales_lag_180,sales_lag_365)

# Reformat date column as a series of numerical predictors
final_train_lags <- final_train_lags %>%
  mutate(
    year = year(date),
    month = month(date),
    day = day(date),
    weekday = wday(date),
    is_weekend = if_else(wday(date) %in% c(1, 7), 1, 0)
  ) %>%
  select(-date)

# Ensure changes have been made
str(final_train_lags)
```

```{r}
# Check to ensure there are no remaining NA values

na_rows <- final_train_lags %>%
  filter(if_any(everything(), is.na))

print(na_rows)

```

```{r}
# Optional test with subset
set.seed(123) 

split <- initial_split(final_train_lags, prop = 0.7)

training_set <- training(split)    # 70% of the data
validation_set <- testing(split)
```


```{r}
# Fit random forest model
rf_model <- ranger(
  formula = sales ~ .,                 
  data = training_set,         
  num.trees = 500,                 
  importance = 'impurity',        
  num.threads = parallel::detectCores(),
  verbose = TRUE
)

# Print model summary
print(rf_model)

# Fit the model on the validation set
rf_pred <- predict(rf_model, data = validation_set)

# Output RMSLE on training set
rmsle_val <- rmsle(validation_set$sales, rf_pred$predictions)
print(rmsle_val)

# Save model as a separate object
save(rf_model, file = "rf_model.rda")
```

```{r}
# Prepare test data to be processed in a random forest
str(final_test_lags)

# Replace NA values in holiday binary predictors with 0
final_test_lags <- final_test_lags %>%
  mutate(national_holiday = ifelse(is.na(national_holiday), 0, national_holiday),
         state_holiday = ifelse(is.na(state_holiday), 0, state_holiday),
         city_holiday = ifelse(is.na(city_holiday), 0, city_holiday))

# Factorize text predictors
final_test_lags <- final_test_lags %>%
  mutate(store_nbr = factor(store_nbr), family = factor(family), city = factor(city), state = factor(state), type = factor(type)) %>%
        dplyr::mutate(across(where(is.factor), as.integer))

# Use forward and backward fill to replace NA values in daily oil price
final_test_lags <- final_test_lags %>%
  arrange(date) %>%
  fill(dcoilwtico, .direction = "down")%>%
  fill(dcoilwtico, .direction = "up")

# Drop the observations with NA values for sales lags (primarily from beginning of dataset)
final_test_lags <- final_test_lags %>%
  arrange(date) %>%
  fill(transactions, .direction = "down")%>%
  fill(transactions, .direction = "up")

# Reformat date column as a series of numerical predictors
final_test_lags <- final_test_lags %>%
  mutate(
    year = year(date),
    month = month(date),
    day = day(date),
    weekday = wday(date),
    is_weekend = if_else(wday(date) %in% c(1, 7), 1, 0)
  ) %>%
  select(-date)

str(final_test_lags)

```

```{r}
# Load random forest model object if necessary

# load("rf_model.rda")

predictions <- predict(rf_model, data = final_test_lags)

pred_val <- cbind(final_test_lags, sales_pred = predictions)

submission <- pred_val %>%
  select(id, prediction) %>%
  rename(sales = prediction)

write.csv(submission, "RF_Model_Submission.csv", row.names = FALSE)
```

```{r}
# Chech which predictors were most significant

vip(rf_model)

```







