---
title: "Correlation Heat Map"
output: html_document
date: "2024-11-14"
---


```{r}

knitr::opts_chunk$set(echo = TRUE)

```


```{r}
# Load necessary libraries
library(tseries)
library(corrplot)
```



```{r}
# load data
final_train_lags <- read_csv("/data/accounts/fa24/garretthayden/DSCI445/FinalProject2/Data/final_train_lags_lasso_rf.csv"))
```

## Stationarity Test

```{r}
# dickey fuller test of stationarity of sales

sales_ts <- final_train_lags$sales

adf_result <- adf.test(sales_ts, alternative = "stationary")

print(adf_result)
```

# As seen by the Dickey

```{r}
# Check cardinality 
categorical_columns <- select(final_train_lags, store_nbr, family, city, state, type)

# Count unique values for each column
cardinality <- sapply(categorical_columns, n_distinct)

# Print cardinality
print(cardinality)

cardinality_ratio <- cardinality / nrow(final_train_lags)

# Print ratio
print(cardinality_ratio)
```



```{r, fig.width=10, fig.height=10}
# Create correlation matrix and plot as a heat map
png("heatmap.png", width = 3200, height = 3200, res = 300)

# Create correlation matrix
cor_matrix <- cor(final_train_lags, use = "complete.obs")

# Plot the correlation matrix as a heatmap
heatmap <- corrplot(
  cor_matrix, 
  method = "color", 
  type = "full", 
  tl.col = "black", 
  tl.srt = 45, 
  addCoef.col = "black", 
  number.cex = 0.7, 
  col = colorRampPalette(c("blue", "white", "red"))(200)
)
# Convert 'family' factor to numeric
final_train_lags$family <- as.numeric(as.factor(final_train_lags$family))  

# Convert 'type' factor to numeric
final_train_lags$type <- as.numeric(as.factor(final_train_lags$type))  

# Replace NA values with 0 for all columns
final_train_lags[is.na(final_train_lags)] <- 0

# Check the structure of the final dataset to confirm the changes
str(final_train_lags)

dev.off()
```





