---
title: "Lauren and Jillian EDA"
output: html_document
date: "2024-11-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# install packages and load libraries
library(parallel)
library(readr)
library(dplyr)
library(leaps)
library(ggplot2)
library(glmnet)
library(ISLR)
library(dials)
library(tidymodels)

#detectCores()
```

```{r}
# load data
final_train_lags <- read_csv("/data/accounts/fa24/garretthayden/DSCI445/Group3FinalProject/Data//final_train_lags.csv")
```


```{r}

# include lasso or linear model to "beat"
# gam or regression spline 
# fit on families of product
# minimize the scope
# scheme to randomly subsample within and over days
# suggestions: 1. save model output anytime you run it, can't necessarily upload it to github
# document collaboration using github
# names of the commits
# use the same data frame

# "stochastic gradient descent" theory random subsets
# multiple randomly selected subsets

# set the number of cores (64) in parallel to a larger value

# store and load the model whenever we need it

# Step 4): Create random forest with all predictors and chosen lags

library(randomForest)
#library(ranger)
library(vip)


unique_values <- unique(subset_train_lags$sales)
length(unique_values)

# Set up random forest specification with tuning parameters
rf_spec <- rand_forest(mtry = floor(sqrt(ncol(subset_train_lags) - 1)), ) %>%
  set_engine("randomForest", importance = TRUE) %>%
  set_mode("regression")

# stopping criteria to reduce size of trees rather than # of trees

# Fit the model using the training data
rf_fit <- rf_spec %>%
  fit(sales ~ ., data = subset_train_lags)

#rf_model <- extract_fit_engine(rf_fit)
#vip(rf_model)

#randomForest::importance(rf_fit) 

#rf_model <- rf_fit$fit

predictions <- predict(rf_fit, new_data = subset_train_lags)

comparison <- data.frame(Actual = subset_train_lags$sales, Predicted = predictions$.pred)

# Calculate RMSE (Root Mean Squared Error)
rmse <- sqrt(mean((comparison$Actual - comparison$Predicted)^2))
print(paste("RMSE: ", round(rmse, 2)))


#rf_spec <- rand_forest(trees = 100, mtry = floor(sqrt(ncol(subset_train_lags) - 1))) %>%
 # set_engine("randomForest", importance = TRUE) %>%
  #set_engine("ranger", importance = "permutation") %>%
 # set_mode("regression")

#rf_fit <- rf_spec %>%
 # fit(sales ~ ., data = subset_train_lags)

#vip(rf_fit)

#summary(rf_fit)

#rf_fit$fit

#predictions <- predict(rf_fit, newdata = subset_train_lags)

#comparison <- data.frame(Actual = subset_train_lags$sales, Predicted = predictions)

#rmse <- sqrt(mean((comparison$Actual - comparison$Predicted)^2))
#print(paste("RMSE: ", round(rmse, 2)))

```
