---
title: "Lasso and Random Forest Final Data Preprocessing"
output: html_document
date: "2024-11-14"
---

```{r setup, include=FALSE}
rm(list = ls())
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Laod libraries and necessary datasets
library(readr)
library(dplyr)
library(lubridate)

final_train_lags <- read_csv("/data/accounts/fa24/garretthayden/DSCI445/FinalProject2/Data//final_train_lags.csv")

final_test_lags <- read_csv("/data/accounts/fa24/garretthayden/DSCI445/FinalProject2/Data/final_test_lags.csv")
```

## Apply final transformations to training data before running Lasso and Random Forest models

```{r}
# Prepare training dataset to be further processed 
str(final_train_lags)

# Replace NA values in holiday binary predictors with 0
final_train_lags_lasso_rf <- final_train_lags %>%
  mutate(national_holiday = ifelse(is.na(national_holiday), 0, national_holiday),
         state_holiday = ifelse(is.na(state_holiday), 0, state_holiday),
         city_holiday = ifelse(is.na(city_holiday), 0, city_holiday))

# Factorize text predictors
final_train_lags_lasso_rf <- final_train_lags_lasso_rf %>%
  mutate(store_nbr = factor(store_nbr), family = factor(family), city = factor(city), state = factor(state), type = factor(type)) %>%
        dplyr::mutate(across(where(is.factor), as.integer))

# Use forward and backward fill to replace NA values in daily oil price
final_train_lags_lasso_rf <- final_train_lags_lasso_rf %>%
  arrange(date) %>%
  fill(dcoilwtico, .direction = "down")%>%
  fill(dcoilwtico, .direction = "up")

# Use forward and backward fill to replace NA transaction values 
final_train_lags_lasso_rf <- final_train_lags_lasso_rf %>%
  arrange(date) %>%
  fill(transactions, .direction = "down")%>%
  fill(transactions, .direction = "up")

# Drop the observations with NA values for sales lags (primarily from beginning of dataset)
final_train_lags_lasso_rf <- final_train_lags_lasso_rf %>%
  drop_na(sales_lag_1, sales_lag_7,sales_lag_30,sales_lag_60,sales_lag_90,sales_lag_180,sales_lag_365)

# Reformat date column as a series of numerical predictors
final_train_lags_lasso_rf <- final_train_lags_lasso_rf %>%
  mutate(
    year = year(date),
    month = month(date),
    day = day(date),
    weekday = wday(date),
    is_weekend = if_else(wday(date) %in% c(1, 7), 1, 0)
  ) %>%
  select(-date)

# Ensure changes have been made
str(final_train_lags_lasso_rf)
```


```{r}
# Check to ensure there are no remaining NA values

na_rows <- final_train_lags %>%
  filter(if_any(everything(), is.na))

print(na_rows)

```

## Apply the same changes to the testing dataset

```{r}
# Prepare test data to be processed in a random forest
str(final_test_lags)

# Replace NA values in holiday binary predictors with 0
final_test_lags_lasso_rf <- final_test_lags %>%
  mutate(national_holiday = ifelse(is.na(national_holiday), 0, national_holiday),
         state_holiday = ifelse(is.na(state_holiday), 0, state_holiday),
         city_holiday = ifelse(is.na(city_holiday), 0, city_holiday))

# Factorize text predictors
final_test_lags_lasso_rf <- final_test_lags_lasso_rf %>%
  mutate(store_nbr = factor(store_nbr), family = factor(family), city = factor(city), state = factor(state), type = factor(type)) %>%
        dplyr::mutate(across(where(is.factor), as.integer))

# Use forward and backward fill to replace NA values in daily oil price
final_test_lags_lasso_rf <- final_test_lags_lasso_rf %>%
  arrange(date) %>%
  fill(dcoilwtico, .direction = "down")%>%
  fill(dcoilwtico, .direction = "up")

# Drop the observations with NA values for sales lags (primarily from beginning of dataset)
final_test_lags_lasso_rf <- final_test_lags_lasso_rf %>%
  arrange(date) %>%
  fill(transactions, .direction = "down")%>%
  fill(transactions, .direction = "up")

# Reformat date column as a series of numerical predictors
final_test_lags_lasso_rf <- final_test_lags_lasso_rf %>%
  mutate(
    year = year(date),
    month = month(date),
    day = day(date),
    weekday = wday(date),
    is_weekend = if_else(wday(date) %in% c(1, 7), 1, 0)
  ) %>%
  select(-date)

str(final_test_lags_lasso_rf)

```

```{r}
# Save the processed data as .csv in the "Data" folder

write.csv(final_train_lags_lasso_rf, "/data/accounts/fa24/garretthayden/DSCI445/FinalProject2/Data/final_train_lags_lasso_rf.csv", row.names = FALSE)

write.csv(final_test_lags_lasso_rf, "/data/accounts/fa24/garretthayden/DSCI445/FinalProject2/Data/final_test_lags_lasso_rf.csv", row.names = FALSE)

```






